### ISSUE TITLE
Failed setup

### ISSUE THREAD

**Issue by LexterS999** [fernandodiacenco/Enabling_DAVIS-TCP#1]
Debian 10 x64, kernel already upgraded to 5.10.24-1~bpo10+1 (2021-03-29) x86_64

Trying this step
git clone https://github.com/lambda-11235/tcp_davis && cd tcp_davis
sudo make

But errors happened

make -C "/lib/modules/5.10.0-0.bpo.5-amd64/build" M= modules
make[1]: Entering directory '/usr/src/linux-headers-5.10.0-0.bpo.5-amd64'
  SYNC    include/config/auto.conf.cmd
sh: 0: Can't open /usr/src/linux-headers-5.10.0-0.bpo.5-common/scripts/mkmakefile
make[3]: *** [/usr/src/linux-headers-5.10.0-0.bpo.5-common/Makefile:548: outputmakefile] Error 127
/usr/src/linux-headers-5.10.0-0.bpo.5-common/Makefile:687: include/config/auto.conf.cmd: No such file or directory
make[2]: *** [/usr/src/linux-headers-5.10.0-0.bpo.5-common/Makefile:709: include/config/auto.conf.cmd] Error 2
make[1]: *** [/usr/src/linux-headers-5.10.0-0.bpo.5-common/Makefile:185: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.0-0.bpo.5-amd64'
make: *** [Makefile:9: all] Error 2

**Comment by LexterS999** [comment]
Doing something like that

nano -w /etc/apt/sources.list
deb http://deb.debian.org/debian buster-backports main
deb-src http://deb.debian.org/debian buster-backports main

sudo apt update
sudo apt install -t buster-backports linux-image-amd64
sudo apt install linux-headers-$(uname -r)

reboot

sudo apt install git
git clone https://github.com/lambda-11235/tcp_davis && cd tcp_davis
sudo make


But still getting error, something wrong with your instruction

**Comment by fernandodiacenco** [comment]
Hmm you are correct

Following my own doc I got errors too, I believe I did something extra at the time that made it compile and forgot to double-check

I will retrace my steps, find what is missing, update the docs and get back to you.

**Comment by fernandodiacenco** [comment]
Ok got it, at the time I first compiled tcp_davis I was playing around patching and compiling the kernel and stuff like that

What was missing is the kernel header files, and I also used a slightly modified make command to make it work

I updated the configuration, tested twice on a Debian 10 VM (by copy / pasting the commands), can you test it too and confirm it is working?

Thanks.

**Comment by LexterS999** [comment]
I thought it will work but no. Made up all like in instructions

sudo cp tcp_davis.ko /lib/modules/`uname -r`
cp: cannot stat 'tcp_davis.ko': No such file or directory

Run depmod
-bash: Run: command not found

sudo sysctl net.ipv4.tcp_congestion_control
net.ipv4.tcp_congestion_control = cubic

modprobe -a tcp_davis
modprobe: WARNING: Module tcp_davis not found in directory /lib/modules/5.10.0-0.bpo.5-cloud-amd64

**Comment by LexterS999** [comment]
So still error's going on. Even on Ubuntu 20.04

**Comment by fernandodiacenco** [comment]
Can you get to this part?

![image](https://user-images.githubusercontent.com/2643364/116312501-e84ed680-a782-11eb-9613-6a2b32de2b39.png)

This is the part where it compiles the module to a file named tcp_davis.ko, then you can copy this file to /lib/modules and continue

I tried again on a Debian 10 virtual machine and it worked, I will spin up an Ubuntu 20.04 vm and check the differences.

**Comment by LexterS999** [comment]
No, as I told you it's getting that error:
/usr/src/tcp_davis# sudo make -C "/usr/src/linux-headers-`uname -r`" M=/usr/src/tcp_davis modules
make: *** /usr/src/linux-headers-5.10.0-0.bpo.5-cloud-amd64: No such file or directory.  Stop.

**Comment by fernandodiacenco** [comment]
So I installed a brand new Ubuntu 20.04.2 LTS VM

It came with most of things pre installed, a high enough kernel version (5.4.x), git, the kernel headers etc

I just had to install build-essential and it compiled successfully

Here is what I did, from install to davis


    sudo apt install build-essential
    
    cd /usr/src && sudo git clone https://github.com/lambda-11235/tcp_davis && cd tcp_davis
    
    sudo make -C "/usr/src/linux-headers-`uname -r`" M=/usr/src/tcp_davis modules
    
    sudo cp tcp_davis.ko /lib/modules/`uname -r`
    
    sudo depmod
    
    sudo nano /etc/modules
    
    add this line at the end and save
    tcp_davis
    
    sudo nano /etc/sysctl.conf
    
    add this line at the end and save
    net.ipv4.tcp_congestion_control=davis
    
    Restart the system and check if its running with:
    sudo sysctl net.ipv4.tcp_congestion_control

So perhaps your install is missing something, can you spin up a VM and test? So far it worked with both Ubuntu and Debian for me so it can't be a coincidence.

**Comment by LexterS999** [comment]
Yeah, it's working on Debian 10 too for now. It was some problem with template ISO on VPS provide side.

But you need to change steps and it must to look like this:
Copy the module file from the git folder to system
sudo cp tcp_davis.ko /lib/modules/`uname -r`

Enable module on startup
sudo nano /etc/modules

Add tcp_davis to the end of the file, save and exit
tcp_davis

sudo depmod

sudo nano /etc/sysctl.conf

Add this line at the end of the file, save and exit
net.ipv4.tcp_congestion_control=davis

Apply the new configuration
sudo sysctl -p

**Comment by fernandodiacenco** [comment]
Wohooo! I'm glad it worked for you. Thanks for the feedback.
